config/routes.rb
Rails.application.routes.draw do
  get 'forum_posts/index'
  get 'forum_threads/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "forum_threads#index"

  resources :forum_threads do  	
  	put :pinit, on: :member
	resources :forum_posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forum_post.rb
class ForumPost < ApplicationRecord
    belongs_to :user
    belongs_to :forum_thread, counter_cache: true

    validates :content, presence: true
end

app/models/forum_thread.rb
class ForumThread < ApplicationRecord
	extend FriendlyId
	friendly_id :title, use: :slugged

	belongs_to :user
	has_many :forum_posts, dependent: :destroy

	validates :title, presence: true, length: {maximum: 30}
	validates :content, presence: true

	def sticky?
		sticky_order != 100
	end

	def pinit!
		self.sticky_order = 1
		self.save
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :forum_threads
  has_many :forum_posts

  enum level: {member: 0, admin: 1}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit
    protect_from_forgery with: :exception
    rescue_from Pundit::NotAuthorizedError, with: :pundit_error
    before_action :callback, if: :devise_controller?

    private

    def pundit_error
        flash[:notice] = 'Not Allowed to edit this Threads !!!'
        redirect_to forum_thread_path()
    end

    def callback
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/forum_posts_controller.rb
class ForumPostsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
  	@threads = ForumThread.friendly.find(params[:forum_thread_id])
  	@post = ForumPost.new(call)

  	@post.forum_thread = @threads
  	@post.user = current_user

  	if @post.save
  		redirect_to forum_thread_path(@threads)
  	else
  		render 'forum_threads/show'
  	end
  end

  private

  def call
  	params.require(:forum_post).permit(:content)
  end
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    if params[:search]
      @threads = ForumThread.where('title ilike ?', "%#{params[:search]}%").paginate(per_page: 5, page: params[:page])
    else
    	@threads = ForumThread.order(sticky_order: :asc).order(id: :desc).paginate(per_page: 5, page: params[:page])
    end
  end

  def show
  	@threads = ForumThread.friendly.find(params[:id])
    @post = ForumPost.new
    @posts = @threads.forum_posts.paginate(per_page: 3, page: params[:page])
  end

  def new
  	@threads = ForumThread.new
  end

  def create
  	@threads = ForumThread.new(call)
  	@threads.user = current_user
  	
  	if @threads.save
  		redirect_to root_path
  	else
  		render 'new'
  	end
  end

  def edit
    @threads = ForumThread.friendly.find(params[:id])
    authorize @threads
  end

  def update
    @threads = ForumThread.friendly.find(params[:id])
    authorize @threads

    if @threads.update(call)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @threads = ForumThread.friendly.find(params[:id])
    authorize @threads

    @threads.destroy

    redirect_to root_path
  end

  def pinit
    @threads = ForumThread.friendly.find(params[:id])
    @threads.pinit!
    redirect_to root_path
  end

  private

  def call
  	params.require(:forum_thread).permit(:title, :content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forum_posts_helper.rb
module ForumPostsHelper
end

app/helpers/forum_threads_helper.rb
module ForumThreadsHelper
end

app/views/forum_posts/index.html.erb
<h1>ForumPosts#index</h1>
<p>Find me in app/views/forum_posts/index.html.erb</p>

app/views/forum_threads/_comment.html.erb
<% if @post.errors.any? %>
	<% @post.errors.full_messages.each do |e| %>
		<div class="alert alert-danger alert-dismissible">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<%= e %></br>
		</div>
	<% end %>
<% end %>

<% if user_signed_in? %>
	<%= form_for [@threads, @post] do |f| %>
		<div class="form-group">
			<%= f.label :comment %>
			<%= f.text_area :content, rows: 10, class: 'form-control' %>
		</div>

		<div class="form-group">
			<%= link_to "Back to Home", root_path, class: 'btn btn-danger', style: 'float: left' %>
			<%= f.submit "Create", class: 'btn btn-success', style: 'float: right' %>
		</div>
	<% end %>
<% end %>

app/views/forum_threads/_form.html.erb
<% if @threads.errors.any? %>
	<% @threads.errors.full_messages.each do |e| %>
		<div class="alert alert-danger alert-dismissible">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<%= e %></br>
		</div>
	<% end %>
<% end %>
<%= form_for @threads do |c| %>
	<div class="form-group">
		<%= c.label :title %>
		<%= c.text_field :title, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= c.label :content %>
		<%= c.text_area :content, rows: 10, class: 'form-control' %>
	</div>

	<div class="form-group">
		<% if @threads.id %>
			<%= link_to "Cancel", forum_thread_path(), class: 'btn btn-danger', style: 'float: left' %>
		<% else %>
			<%= link_to "Cancel", root_path, class: 'btn btn-danger', style: 'float: left' %>
		<% end %>
		<% if @threads.id %>
			<%= c.submit "Update", class: 'btn btn-primary', style: 'float: right' %>
		<% else %>
			<%= c.submit "Create", class: 'btn btn-success', style: 'float: right' %>
		<% end %>
	</div>
<% end %>

app/views/forum_threads/edit.html.erb
<%= render 'layouts/navbar' %>
<div class="col-md-6 offset-md-3">
	<%= render 'form' %>
</div>

app/views/forum_threads/index.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
	<div class="row">
		<div class="col-md-6 offset-md-3">
			<% if user_signed_in? %>
				<%= link_to "Create new Thread", new_forum_thread_path, class: 'btn btn-success', style: 'margin-bottom: 10px' %>
			<% end %>

			<% @threads.each do |t| %>
				<div class="thread">
					<h4>
						<%= link_to t.title.titleize, forum_thread_path(t) %> 
						<% if t.sticky? %>
							<%= octicon "pin", :height => 24, style: 'transform: rotate(90deg)' %>
						<% end %>
					</h4>

					<div class="meta">
						<%= t.created_at.strftime(" %d %B %Y ") %> oleh <%= t.user.name %>
					</div>
					
					<div class="content">
						<%= truncate t.content, length: 30 %>
					</div>

					<div class="action">
						<%= link_to 'Pin It', pinit_forum_thread_path(t), class: 'btn btn-primary', method: :put %>
					</div>

					<div class="count">
						<%= t.forum_posts.count %> obrolan
					</div>
					<div style="clear: both"></div>
				</div>
			<% end %>

			<%= will_paginate @threads, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
		</div>
	</div>
</div>

app/views/forum_threads/new.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
	<div class="col-md-6 offset-md-3">
		<%= render 'form' %>
	</div>
</div>

app/views/forum_threads/show.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
	<div class="row">
		<div class="col-md-6 offset-md-3">
			<div class="thread">
				<h4><%= @threads.title.titleize %></h4>

				<div class="meta">
					<%= @threads.created_at.strftime(' %d %B %Y') %> oleh <%= @threads.user.name %>
				</div>
				
				<div class="content">
					<%= @threads.content %>
				</div>

				<% if policy(@threads).edit? %>
					<div class="action-edit">
						<%= link_to 'Edit', edit_forum_thread_path(@threads), class: 'btn btn-primary' %>
						<% if policy(@threads).destroy? %>
							<%= link_to 'Delete', forum_thread_path(@threads), method: :delete, data: {confirm: 'Do you want to delete this Thread ?'}, class: 'btn btn-danger', style: 'margin-left: 2%' %>
						<% end %>
					</div>
				<% end %>
			</div>

			<% if @threads.forum_posts.any? %>
				<% @posts.each do |p| %>
					<div class="thread">
						<div class="meta">
							<%= p.created_at.strftime(' %d %B %Y') %> oleh <%= p.user.name %>
						</div>
						
						<div class="content">
							<%= p.content %>
						</div>
					</div>
				<% end %>

				<%= will_paginate @threads, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
			<% else %>
				<div>
					Be the first person to comment.
				</div>
			<% end %>

			<%= render 'comment' %>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<div class="row">
	<div class="col-md-6 offset-md-3">
		<%= @threads.each do |t| %>
			<div class="thread">
				<h4><%= t.title %></h4>

				<div class="meta">
					23 Febuari 2021 oleh Zhofran Dhiqo
				</div>
				<div class="content">
					ini mah cm test doang jd ngak perlu panjang" tinggal copas" ajh
					ini mah cm test doang jd ngak perlu panjang" tinggal copas" ajh
					ini mah cm test doang jd ngak perlu panjang" tinggal copas" ajh
				</div>
				<div class="count">
					10 obrolan
				</div>
				<div style="clear: both"></div>
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Forum', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= form_tag root_path, method: :get, class: 'form-inline my-2 my-lg-0' do %>
          <div class="form-group">
            <%= text_field_tag :search, nil, class: 'form-control mr-sm-2' %>
          </div>
          <%= submit_tag "Cari", class: 'btn btn-outline-success my-2 my-sm-0' %>
        <% end %>
      </li>
    </ul>
     <ul class="navbar-nav">
       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= user_signed_in? ? current_user.name : 'Hii Guest' %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <%= link_to "Log Out", destroy_user_session_path, class: 'dropdown-item', method: :delete %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path, class: 'dropdown-item' %>
            <%= link_to "Login", new_user_session_path, class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>
     </ul> 
  </div>
</nav>


<% flash.each do |key, value| %>
  <center>
    <div class="alert alert-success alert-dismissible" style="width: 30%;">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= value %></br>
    </div>
  </center>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phantom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <%= yield %>
  </body>
</html>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<!-- <script type="text/javascript">
  // Get the video
  var video = document.getElementById("myVideo");

  // Get the button
  var btn = document.getElementById("myBtn");

  // Pause and play the video, and change the button text
  function myFunction() {
    if (video.paused) {
      video.play();
      btn.innerHTML = "Pause";
    } else {
      video.pause();
      btn.innerHTML = "Play";
    }
  }
</script> -->